### ISSUE TITLE
Use client-side instead of server-side ga tracking

### ISSUE THREAD

**Issue by funnyprinter** [ronalfy/wordpress-gravity-forms-event-tracking#21]
Hi,

As commendet in https://github.com/nathanmarks/wordpress-gravity-forms-event-tracking/issues/20 I'd like to suggest client side ga tracking.

Why don't you fire the google analytics tracking events on client side? You could add support for both, manual ga universal analytics as well as seo by yoast.

This would solve the client id issue with ga universal analytics. I think this should be fixed, since it is really important to make the user association for conversion tracking (eg. in AdWords).

Further client side tracking would also solve the issue with opt-outs and not tracking logged in users, since if google analytics is missing (eg. yoast removes ga for logged in users) no tracking would be fired. Also blocking ip or using a ga block plugin would be supported this way.

Best and thx for the plugin,

Manuel

**Comment by ronalfy** [comment]
We do this because JavaScript is super unreliable, and I've been working with JS for quite a while.

I've had too many reports if JS errors screwing up analytics (not with this plugin).

Plus, the edge cases are enormous, so we opted for a server-to-server approach. 

What we can do is provide a hook for you so you can send your own custom events, but even that would be unreliable.

Not a good solution here I am afraid.
